apiVersion: 1

datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: system_metrics
    user: grafana
    secureJsonData:
      password: grafana123
    jsonData:
      httpMode: GET
    isDefault: true
    editable: false
    uid: DS_INFLUXDB
